apiVersion: v1
kind: ConfigMap
metadata:
  name: eventhorizon-config
  namespace: eventhorizon
data:
  DEBUG: "0"
  ALLOWED_HOSTS: "api.eventhorizon.local"
  CORS_ALLOWED_ORIGINS: "https://app.eventhorizon.local"
  SOROBAN_RPC_URL: "https://soroban-testnet.stellar.org"
  HORIZON_URL: "https://horizon-testnet.stellar.org"
  STELLAR_NETWORK_PASSPHRASE: "Test SDF Network ; September 2015"
