apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eventhorizon
  namespace: eventhorizon
spec:
  ingressClassName: nginx
  rules:
    - host: api.eventhorizon.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eventhorizon-backend
                port:
                  number: 80
