apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eventhorizon-secrets
  namespace: eventhorizon
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: eventhorizon-secrets
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: eventhorizon/SECRET_KEY
    - secretKey: DATABASE_URL
      remoteRef:
        key: eventhorizon/DATABASE_URL
    - secretKey: REDIS_URL
      remoteRef:
        key: eventhorizon/REDIS_URL
    - secretKey: CELERY_BROKER_URL
      remoteRef:
        key: eventhorizon/CELERY_BROKER_URL
    - secretKey: CELERY_RESULT_BACKEND
      remoteRef:
        key: eventhorizon/CELERY_RESULT_BACKEND
    - secretKey: EVENTHORIZON_CONTRACT_ID
      remoteRef:
        key: eventhorizon/EVENTHORIZON_CONTRACT_ID
    - secretKey: INDEXER_SECRET_KEY
      remoteRef:
        key: eventhorizon/INDEXER_SECRET_KEY
